In [1]:
import re
from nltk.corpus import stopwords
import pandas as pd
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import unidecode
import numpy as np

In [2]:
# import nltk
# nltk.download('stopwords')

In [3]:
df = pd.read_csv('imdb_master.csv', sep=',', encoding ='ISO-8859-1')

In [4]:
df.head()

,Unnamed: 0,Unnamed: 0.1,type,review,label,file,reviews_sem_acentos,reviews_pre_processadas
0,0,0,test,Once again Mr. Costner has dragged out a movie...,neg,0_2.txt,Once again Mr. Costner has dragged out a movie...,mr costner dragged movie far longer necessary ...
1,1,1,test,This is an example of why the majority of acti...,neg,10000_4.txt,This is an example of why the majority of acti...,example majority action films generic boring r...
2,2,2,test,"First of all I hate those moronic rappers, who...",neg,10001_1.txt,"First of all I hate those moronic rappers, who...",first hate moronic rappers could nt act gun pr...
3,3,3,test,Not even the Beatles could write songs everyon...,neg,10002_3.txt,Not even the Beatles could write songs everyon...,even beatles could write songs everyone liked ...
4,4,4,test,Brass pictures (movies is not a fitting word f...,neg,10003_3.txt,Brass pictures (movies is not a fitting word f...,brass pictures movies fitting word really some...

In [ ]:
def pre_processamento_de_linha(texto):
     
    # Remove tudo que não forem letras
    letters_only_text = re.sub("[^a-zA-Z]", " ", texto)

    # Converte palavras para minúsculo e as separa
    words = letters_only_text.lower().split()

    # Remove stopwords
    set_stopwords = set(stopwords.words("english"))
    meaningful_words = [w for w in words if w not in set_stopwords]
    
    # Extrai as raízes das palavras
    # ps = PorterStemmer()
    # stemmed_words = [ps.stem(word) for word in meaningful_words]
    
    # Transforma set de palavras em lista
    texto_limpo = " ".join(meaningful_words)

    return texto_limpo

In [ ]:
df['reviews_sem_acentos'] = [unidecode.unidecode(texto) for texto in  df['review']]

In [ ]:
df['reviews_pre_processadas'] = df['reviews_sem_acentos'].apply(lambda linha : pre_processamento_de_linha(linha))

In [ ]:
df.to_csv('imdb_master.csv')

In [5]:
reviews_pre_processadas = df['reviews_pre_processadas']

In [6]:
def tokenizar(sentencas):
    words = []
    for sentenca in sentencas:
        words.extend(sentenca)
        words = sorted(list(set(words)))
    return words

In [7]:
palavras_tokenizadas = tokenizar(reviews_pre_processadas[:10])

In [8]:
palavras_tokenizadas

[' ',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [9]:
# def gerar_bag_of_words(sentencas):        
    # vocab = tokenizar(sentencas)
    # matriz = []
    # print("Lista de palavras dos textos: \n{0} \n".format(vocab));
    # for sentenca in sentencas:             
        # bag_vector = np.zeros(len(vocab))        
        # for w in sentenca:            
            # for i,word in enumerate(vocab):                
                # if word == w:                     
                    # bag_vector[i] += 1
                    
            # matriz.append(bag_vector)
        # print("{0}\n{1}\n".format(sentenca,np.array(bag_vector)))
    # # return pd.DataFrame(list(matriz)).T
    # return matriz

In [10]:
#count_vectorizer = TfidfVectorizer(stop_words='english')
count_vectorizer = TfidfVectorizer()
matriz_esparsa = count_vectorizer.fit_transform(reviews_pre_processadas[0:1000])

In [11]:
doc_term_matrix = matriz_esparsa.todense()

df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names(), 
                  index= df[0:1000].index)
df

,aa,aaja,aap,aaron,abandon,abandoned,abandoning,abandons,abbot,abbott,...,zones,zontar,zoo,zoom,zooming,zooms,zubeidaa,zucker,zulu,zzzzzzzzzzzzz
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
similiaridade =  pd.DataFrame(cosine_similarity(df, df))

In [20]:
similiaridade.head()

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,1.000000,0.026242,0.039598,0.040534,0.016972,0.015121,0.031422,0.026768,0.006415,0.016148,...,0.020225,0.011366,0.067987,0.017637,0.046948,0.005597,0.024843,0.021278,0.012906,0.019942
1,0.026242,1.000000,0.093822,0.195603,0.053588,0.044275,0.032317,0.040091,0.017744,0.013073,...,0.045283,0.052227,0.033944,0.027971,0.038987,0.039426,0.095754,0.028900,0.049917,0.033083
2,0.039598,0.093822,1.000000,0.148211,0.049608,0.021697,0.090756,0.064640,0.012719,0.006560,...,0.056637,0.054053,0.079081,0.011391,0.041714,0.066880,0.105846,0.074460,0.074627,0.091280
3,0.040534,0.195603,0.148211,1.000000,0.018749,0.039738,0.036113,0.062139,0.011889,0.017464,...,0.038813,0.037784,0.059563,0.021031,0.044049,0.055471,0.060774,0.045186,0.036227,0.010013
4,0.016972,0.053588,0.049608,0.018749,1.000000,0.004741,0.053136,0.041707,0.014306,0.034534,...,0.044282,0.022876,0.037304,0.003840,0.016996,0.032228,0.041580,0.042151,0.026293,0.030745

In [ ]:
print(doc_term_matrix)